### ISSUE TITLE
Typescript definitions are broken in 0.7.1

### ISSUE THREAD

**Issue by mkraeva-astea** [kubernetes-client/javascript#156]
The 0.7.1 release has broken the typescript definitions - running `tsc` on the example for listing all pods, I get numerous errors like
> node_modules/@kubernetes/client-node/dist/api.d.ts:13:26 - error TS7016: Could not find a declaration file for module 'request'. '/home/marina/kube-dep-test/node_modules/request/index.js' implicitly has an 'any' type.

The typings work in v0.6.0; v0.7.0 compiles successfully as well, but I get the runtime error described in #135.

**Comment by brendandburns** [comment]
hrm, I will try to figure out what is missing here.  Apologies!

**Comment by brendandburns** [comment]
Looks like this was fixed by #138 I'll cut a new release...

**Comment by brendandburns** [comment]
Apologies for the delay, I finally pushed `0.7.2` please try and see if it fixes things.

Thanks!

**Comment by mkraeva-astea** [comment]
Unfortunately, v0.7.2 doesn't work either.

I made a minimal reproducible example here: https://github.com/mkraeva-astea/kube-client-typescript-example.

The example uses v0.6.0 and compiles correctly -  `npm install && npm run build` runs successfully and `npm test` lists my local pods.
If you then run `npm install @kubernetes/client-node@0.7.2 --save-exact` and try to rebuild, you can see multiple errors, e.g.
> Could not find a declaration file for module 'ws'. '/home/marina/kube-dep-test/node_modules/ws/index.js' implicitly has an 'any' type.

**Comment by drakedevel** [comment]
@mkraeva-astea it looks like the issue is missing type dependencies (specifically `@types/ws @types/node @types/request`)

If I add those, your example builds for me:

```
[adrake@fbox /tmp/kube-client-typescript-example (master)]$ npm install && npm run build 
<...snip...>

added 121 packages from 185 contributors and audited 151 packages in 2.529s
found 0 vulnerabilities


> kube-dep-test@1.0.0 build /tmp/kube-client-typescript-example
> rm -rf dist && tsc

[adrake@fbox /tmp/kube-client-typescript-example (master)]$ npm install @kubernetes/client-node@0.7.2 --save-exact
npm WARN deprecated nomnom@1.5.2: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN kube-dep-test@1.0.0 No description
npm WARN kube-dep-test@1.0.0 No repository field.

+ @kubernetes/client-node@0.7.2
added 21 packages from 11 contributors, removed 17 packages, updated 2 packages and audited 156 packages in 0.998s
found 0 vulnerabilities

[adrake@fbox /tmp/kube-client-typescript-example (master *)]$ npm run build 

> kube-dep-test@1.0.0 build /tmp/kube-client-typescript-example
> rm -rf dist && tsc

<...snip...>

Found 22 errors.

<...snip...>

[adrake@fbox /tmp/kube-client-typescript-example (master *)]$ npm install --save @types/ws @types/node @types/request
<...snip...>
added 7 packages from 53 contributors and audited 166 packages in 0.782s
found 0 vulnerabilities

[adrake@fbox /tmp/kube-client-typescript-example (master *)]$ npm run build 

> kube-dep-test@1.0.0 build /tmp/kube-client-typescript-example
> rm -rf dist && tsc

[adrake@fbox /tmp/kube-client-typescript-example (master *)]$ 
```

**Comment by flyboarder** [comment]
@brendandburns as per this SO post, they should be in `devdependencies`
https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies

**Comment by brendandburns** [comment]
@flyboarder I actually am not sure, we use the `request` library in our public API:

https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L117

(specifically the `applyToRequest(...)` call)

So per that SO post, I think we _do_ need it in `dependencies`

**Comment by flyboarder** [comment]
@brendandburns I took another look at the answer post, you are correct! We do need the types in dependencies for consuming projects to understand relevant types.
