### ISSUE TITLE
Informer from example does not work with 1.0.0-rc2

### ISSUE THREAD

**Issue by floriankoch** [kubernetes-client/javascript#1189]
**Describe the bug**

I try to build an Informer , and used this example
https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/informer/informer.ts

It fails without modification

src/main.ts:13:79 - error TS2345: Argument of type '() => Promise<k8s.V1PodList>' is not assignable to parameter of type 'ListPromise<KubernetesObject>'.
  Type 'Promise<V1PodList>' is not assignable to type 'Promise<{ response: IncomingMessage; body: KubernetesListObject<KubernetesObject>; }>'.
    Type 'V1PodList' is missing the following properties from type '{ response: IncomingMessage; body: KubernetesListObject<KubernetesObject>; }': response, body

13 const informer = k8s.makeInformer(kc, `/api/v1/namespaces/${namespace}/pods`, listFn);
                                                                                 ~~~~~~

**To Reproduce**
try to build the example https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/informer/informer.ts with 1.0.0-rc2

**Expected behavior**
example works with 1.0.0-rc2

**Comment by floriankoch** [comment]
@brendandburns   sorry linked  from the wrong branch , i use the example from the release-1.x. branch

**Comment by mstruebing** [comment]
For me it works in the 1.x branch on the latest commit.
Do you use the version published on npm? This version is a bit older and doesn't contain all the latest changes.

**Comment by floriankoch** [comment]
@mstruebing   yes is use the published version "@kubernetes/client-node": "^1.0.0-rc2",

**Comment by floriankoch** [comment]
@brendandburns @mstruebing   works with the latest commit from the release-1.x branch
